/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Julien' at '1/25/16 8:52 PM' with Gradle 2.10
 *
 * @author Julien, @date 1/25/16 8:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
